library(datasets)
library(dplyr)
library(stats)
library(stats4)
library(ggplot2)
library(readr)
library(fBasics)
library(plotrix)
Datas <- read_csv("C:\\Users\\bigfo\\Desktop\\progetto tech\\TesiAndreaGurioliContracts\\Dati_ping_tesi_Andrea_Gurioli_rilevazioni_01_02_2020_02_02_2020.csv")
View(Datas)
meanTime<-aggregate(pingtime_SEC ~ gasprice_GWEI, data=Datas, FUN=mean)
meanTime
plot(meanTime$gasprice_GWEI,meanTime$pingtime_SEC,type='o',col='red',lwd=2)
DeviazioneStandardGP<-aggregate(pingtime_SEC ~ gasprice_GWEI, data=Datas, FUN=sd)
DeviazioneStandardGP
DeviazioneStandardGP<-rename(DeviazioneStandardGP, deviazione_standard='pingtime_SEC')
plot(DeviazioneStandardGP$gasprice_GWEI,DeviazioneStandardGP$deviazione_standard,type='h',col='blue',lwd=4)
